flatcar_ami           = "ami-0b177b95890e9beaa"
ec2_user              = "core"
aws_availability_zone = "eu-central-1a"
public_key_path       = "./kubernetes-cluster.pub"
private_key_path       = "./kubernetes-cluster"
