apiVersion: v1
kind: Namespace
metadata:
  name: audit-test
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: audit-test
spec:
  containers:
    - name: nginx
      image: nginx

