apiVersion: v1
kind: Secret
metadata:
  name: test-mount-secret
data:
  content: c3VwZXItc2VjdXJlLWFwaS1rZXkK
---
apiVersion: v1
kind: Pod
metadata:
  name: test-secret-file
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: test-mount-secret
  containers:
    - name: alpine
      image: alpine
      command: [ "sh", "-c", "ls -l /etc/secret-volume; echo \"File content: $(cat /etc/secret-volume/content)\""]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"