apiVersion: v1
kind: Secret
metadata:
  name: test-credenitals-env-vars
type: Opaque
data:
  SECRET_KEY: bXktcGFzc3dvcmQK
---
apiVersion: v1
kind: Pod
metadata:
  name: test-credenitals-env-vars
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "sh", "-c", "printenv | grep SECRET_KEY" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: test-credenitals-env-vars
          key: SECRET_KEY
  
