apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-configmap
  namespace: tests
data:
  foo: "bar"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-configmaps
  namespace: tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-configmaps
  namespace: tests
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-configmap-reader
  namespace: tests
subjects:
- kind: ServiceAccount
  name: read-configmaps
roleRef:
  kind: Role
  name: read-configmaps
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: tests
spec:
  serviceAccountName: read-configmaps
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "Testing configmaps access:"
      kubectl get configmaps
      
      echo ""
      echo "Read custom-configmap data"
      kubectl get configmap custom-configmap -o jsonpath='{.data}'

      echo ""
      echo "Testing secrets access"
      kubectl get secrets

      echo ""
      echo "Testing configmaps access from another namespaces"
      kubectl get configmaps -n default

      echo ""
      echo "Tests done, exiting"
      exit 0