apiVersion: v1
kind: Pod
metadata:
  name: seccomp-denied-test
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: test
    image: alpine
    command:
    - sh
    - -c
    - |
      apk add --no-cache strace gdb
      echo "Seccomp status:"
      grep Seccomp /proc/self/status
      echo "Trying ptrace syscall..."
      strace -e ptrace gdb --batch --pid 1