apiVersion: v1
kind: Pod
metadata:
  name: security-context-test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  volumes:
  - name: security-context-test
    emptyDir: {}
  containers:
  - name: security-context-test
    image: ubuntu
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
  
## TEST
# Touch a file with readOnlyRootFilesystem: true
# Run as root but block some capabilities
# - kill an sleep process without KILL capabiliy
# Run test as user 1000 ('ubuntu' user in ubuntu official images)
