apiVersion: v1
kind: Pod
metadata:
  name: runasuser-id-test
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: [ "sh", "-c", "whoami && id; sleep 3600" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
