apiVersion: v1
kind: Pod
metadata:
  name: no-kill-nginx-test
spec:
  containers:
  - name: nginx
    image: nginx
    command: [ "sh", "-c", "nginx && sleep 5 && kill $(pidof nginx) || echo 'cannot kill nginx'" ]
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - KILL
