---
- name: Undo cluster setup
  hosts: server
  gather_facts: true
  become: true
  tasks:
  - name: Apply Calico tigera-operator manifest
    ansible.builtin.shell: |
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/operator-crds.yaml
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/tigera-operator.yaml

  - name: Wait for tigera-operator deployment to be available
    ansible.builtin.shell: |
      kubectl wait --for=condition=Available deployment/tigera-operator -n tigera-operator --timeout=180s
    register: wait_result
    retries: 3
    delay: 30
    until: wait_result.rc == 0

  - name: Apply Calico custom resources manifest
    ansible.builtin.shell: |
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/custom-resources.yaml


