---
- name: Fetch kubeconfig from worker node
  hosts: server
  become: yes
  tags: ["kubeconfig"]
  tasks:
    - name: Fetch kubeconfig
      fetch:
        src: /home/ec2-user/.kube/config
        dest: /tmp/k3s.yaml
        flat: yes

- name: Copy kubeconfig to bastion
  hosts: bastion
  become: yes
  tags: ["kubeconfig"]
  tasks:
    - name: Create .kube directory
      file:
        path: /home/ec2-user/.kube
        state: directory
    
    - name: Copy kubeconfig to bastion
      copy:
        src: /tmp/k3s.yaml
        dest: /home/ec2-user/.kube/config
        owner: ec2-user
        group: ec2-user
        mode: '0600'

    - name: Replace old IP with current server IP in kubeconfig
      replace:
        path: /home/ubuntu/k3s.yaml
        regexp: 'server: https://.*:6443'
        replace: "server: https://{{ hostvars['agent'].ansible_host }}:6443"