- name: Create cluster
  import_playbook: k3s-ansible/playbooks/site.yml
- name: Configure Calico
  import_playbook: calico.yaml
- name: Create bastion kubectl confing
  import_playbook: set-bastion.yaml